import { supabase } from "@/integrations/supabase/client";

/**
 * Seed data matching the screenshots
 * This initializes the database with sample data for demonstration
 */

export async function seedDatabase() {
  try {
    const { data: user } = await supabase.auth.getUser();
    if (!user.user) {
      console.error("No user logged in");
      return false;
    }

    const userId = user.user.id;

    // Check if data already exists
    const { data: existingProducts } = await supabase
      .from("products")
      .select("id")
      .eq("user_id", userId)
      .limit(1);

    if (existingProducts && existingProducts.length > 0) {
      console.log("Data already exists. Use toggleSeedData() to refresh.");
      return false;
    }

    // Seed Products (matching screenshots)
    const productsToInsert = [
      {
        name: "Rice",
        price: 1000,
        stock: 800,
        category: "Grains",
        min_stock: 10,
        user_id: userId,
      },
      {
        name: "Bean",
        price: 100,
        stock: 180,
        category: "Legumes",
        min_stock: 10,
        user_id: userId,
      },
    ];

    const { data: productsData, error: productsError } = await supabase
      .from("products")
      .insert(productsToInsert)
      .select();

    if (productsError) {
      console.error("Error seeding products:", productsError);
      return false;
    }

    const beanProduct = productsData?.find((p: any) => p.name === "Bean");

    // Seed Sales (matching screenshot: RWF 9,900 from Bean sale)
    if (beanProduct) {
      const salesToInsert = [
        {
          product_id: beanProduct.id,
          product_name: "Bean",
          quantity: 99,
          total: 9900,
          date: "2026-04-04",
          employee_name: "nick",
          user_id: userId,
        },
      ];

      const { error: salesError } = await supabase
        .from("sales")
        .insert(salesToInsert);

      if (salesError) {
        console.error("Error seeding sales:", salesError);
        // Don't return false, continue with seed
      }
    }

    // Seed Stock Entries (matching screenshot stock movement history)
    if (beanProduct) {
      const stockEntriesToInsert = [
        {
          product_id: beanProduct.id,
          product_name: "Bean",
          type: "out",
          quantity: 700,
          date: "2026-04-04",
          note: "nn",
          user_id: userId,
        },
        {
          product_id: beanProduct.id,
          product_name: "Bean",
          type: "in",
          quantity: 80,
          date: "2026-04-04",
          note: "note",
          user_id: userId,
        },
      ];

      const { error: stockError } = await supabase
        .from("stock_entries")
        .insert(stockEntriesToInsert);

      if (stockError) {
        console.error("Error seeding stock entries:", stockError);
        // Don't fail on this
      }
    }

    // Note: Expenses are kept at RWF 0 as shown in screenshots
    // Activity logs are typically auto-generated by database triggers

    // Make window.seedDatabase available for console access
    (window as any).seedDatabase = seedDatabase;
    (window as any).toggleSeedData = toggleSeedData;

    console.log("✓ Database seeded successfully!");
    console.log(
      "To refresh data, run: toggleSeedData()\nTo view this data, run: window.location.reload()"
    );
    return true;
  } catch (error) {
    console.error("Seeding error:", error);
    return false;
  }
}

/**
 * Toggle seed data - useful for resetting the database
 */
export async function toggleSeedData() {
  try {
    const { data: user } = await supabase.auth.getUser();
    if (!user.user) {
      console.error("No user logged in");
      return false;
    }

    const userId = user.user.id;

    // Delete existing data
    await supabase.from("stock_entries").delete().eq("user_id", userId);
    await supabase.from("sales").delete().eq("user_id", userId);
    await supabase.from("expenses").delete().eq("user_id", userId);
    await supabase.from("products").delete().eq("user_id", userId);

    // Re-seed
    return await seedDatabase();
  } catch (error) {
    console.error("Toggle seed error:", error);
    return false;
  }
}
